### PR TITLE
Ensure empty collection is not queried for last result. Fixes #71

### LINKED ISSUE #71: NoSuchElementException triggered by snippetEventsCurrentSnippets.getLast()
**Describe the bug**
Executing a notebook shows NoSuchElementException due to empty collection in snippetEventsCurrentSnippets.getLast()

**To Reproduce**
Load a notebook with serious compile errors

**Expected behavior**
all errors are visible, no problems hidden

### PR DESCRIPTION
**Pull request by svenreimers**

### CODE REVIEW

File: shell/src/main/java/org/jtaccuino/jshell/ReactiveJShell.java [hunk 1]
```diff
@@ -103,26 +103,32 @@ public EvaluationResult eval(String string) {
...
+                    var varName = e.name();
+                    var varType = sourceCodeAnalysis().analyzeType(varName,
+                            varName.length());
+                    var varValue = lastEvent.value();
+                    yield new EvaluationResult(snippetEventsCurrentSnippets, snippetEventsInfluencedSnippets,
+                    ResultStatus.SUCCESS, Optional.of(varValue), Optional.of(varType));
+                }
+                default ->
+                    new EvaluationResult(snippetEventsCurrentSnippets, snippetEventsInfluencedSnippets,
+                    ResultStatus.SUCCESS, Optional.empty(), Optional.empty());
```
Comment (mklaehn) [inline shell/src/main/java/org/jtaccuino/jshell/ReactiveJShell.java:127]: you could return null here and have the following orElse turn it into the nondescript SUCCESS EvaluationResult
```suggestion
                    null;
```

File: shell/src/main/java/org/jtaccuino/jshell/ReactiveJShell.java [hunk 2]
```diff
@@ -103,26 +103,32 @@ public EvaluationResult eval(String string) {
...
+            }).orElse(new EvaluationResult(snippetEventsCurrentSnippets, snippetEventsInfluencedSnippets,
```
Comment (mklaehn) [inline shell/src/main/java/org/jtaccuino/jshell/ReactiveJShell.java:128]: using orElseGet prevent unnecessary creation of the nondescript SUCCESS EvaluationResult
```suggestion
            }).orElseGet(() -> new EvaluationResult(snippetEventsCurrentSnippets, snippetEventsInfluencedSnippets,
```

**Review by mklaehn — DISMISSED** [review]
